### PR TITLE
feat(login): Enable users to login

### PR DESCRIPTION
**Pull request by armstrongsouljah**
#### What does this Pr do?
- Adds an implementation to enable users to log into the store manager application

#### Description of the task to be implemented
- Add login form
- Add login view
- Connect login view to the redux store
- Test the login component

#### How can this be manually tested?
- Fetch this branch locally by running `git fetch origin ft-user-login-164352913 && git checkout ft-user-login-164352913`
- Install project dependencies `yarn install`
- Start the development server `yarn start`.

#### What are the related pivotal stories?
[#164352913](https://www.pivotaltracker.com/story/show/164352913)

### CODE REVIEW

**Review by MuhweziDeo — APPROVED** [review]
LGTM

**Review by MuhweziDeo — DISMISSED** [review]
LGTM

**Comment by MuhweziDeo** [comment]
FIX DUPLICATIONS

**Comment by MuhweziDeo** [comment]
Oh exclude tests from codeclimate

**Comment by armstrongsouljah** [comment]
@MuhweziDeo I have excluded the tests. Do I need to push again to fix this?

**Review by calvinpete — APPROVED** [review]
LGTM

**Pull request merged**
